### PR TITLE
values_string

### PR DESCRIPTION
**Pull request by mathieu-benoit**
https://humanitec.slack.com/archives/CFLTYLGVB/p1721408939283169

https://humanitec.atlassian.net/browse/DOCS-719

Based on this: https://github.com/humanitec/terraform-provider-humanitec/commit/0b6a10cfc386302386a730ef712e197dd10af6a5.

### CODE REVIEW

**Comment by mathieu-benoit** [comment]
Ready for your review, thanks!

**Comment by TobiasBabin** [comment]
> Ready for your review, thanks!

Thanks so much for the initiative! I found some more occurrences of `secrets` which IMO must be `secrets_string` and pushed a commit accordingly.

**Comment by mathieu-benoit** [comment]
> I found some more occurrences of secrets which IMO must be secrets_string and pushed a commit accordingly.
Oh yeah, really true, good catch!

**Review by TobiasBabin — APPROVED** [review]
LGTM 🚀

**Pull request merged**
